  <div id="footer-wrapper" class="container-fluid">
    <footer id="main-footer" class="container">
        <div class="row">
          <div class="col-md-2 col-md-offset-1">
            <h3>INFORMATION</h3>
            <ul>
              <li>
                <a href="#">About Us</a>
              </li>
              <li>
                <a href="#">Delivery Information</a>
              </li>
              <li>
                <a href="deliverytime.shtml">Delivery Time Slots</a>
              </li>
              <li>
                <a href="terms.shtml">Terms & Conditions</a>
              </li>
            </ul>
          </div>
          <div class="col-md-2 col">
            <h3>SERVICES</h3>
            <ul>
              <li>
                <a href="ourfood.shtml">Our Food</a>
              </li>
              <li>
                <a href="#">Catering</a>
              </li>
              <li>
                <a href="#">Delivery</a>
              </li>
              <li>
                <a href="#">Order Online</a>
              </li>
            </ul>
          </div>
          <div class="col-md-2">
            <h3>EXTRAS</h3>
            <ul>
              <li>
                <a href="promotions.shtml">Promotions</a>
              </li>
              <li>
                <a href="#">Specials</a>
              </li>
              <li>
                <a href="careers.shtml">Careers</a>
              </li>
            </ul>
          </div>
          <div class="col-md-2">
            <h3>CONTACT</h3>
            <ul>
              <li>
                <p>Delivery Hotline:</p>
                <p><a href="tel:63859122">6385 9122</a> / <a href="tel:63859133">6385 9133</a></p>
                <a href="ouroutlets.shtml">Outlets</a>
              </li>
            </ul>
          </div>
          <div class="col-md-3">
            <h3>SHARE WITH US</h3>
            <ul>
              <li>
                <a class="facebook" href="https://www.facebook.com/leeweebrothers"></a>
                <a class="twitter" href="#"></a>
                <a class="instagram" href="#"></a>
              </li>
              <li><p class="copy-right">&copy; LEE WEE & BROTHERS' PTE LTD.</p></li>
            </ul>
          </div>
        </div>
    </footer>
  </div>
</div>