<div id="footer-wrapper" class="container-fluid">
  <footer id="main-footer" class="container">
      <div class="row">
        <div class="col-md-2 col-md-offset-1">
          <h3>INFORMATION</h3>
          <ul>
            <li>
              <a href="#">About Us</a>
            </li>
            <li>
              <a href="#">Delivery Information</a>
            </li>
            <li>
              <a href="#">Delivery Time Slots</a>
            </li>
            <li>
              <a href="#">Terms & Conditions</a>
            </li>
          </ul>
        </div>
        <div class="col-md-2 col">
          <h3>SERVICES</h3>
          <ul>
            <li>
              <a href="#">Our Food</a>
            </li>
            <li>
              <a href="#">Catering</a>
            </li>
            <li>
              <a href="#">Delivery</a>
            </li>
            <li>
              <a href="#">Order Online</a>
            </li>
          </ul>
        </div>
        <div class="col-md-2">
          <h3>EXTRAS</h3>
          <ul>
            <li>
              <a href="#">Promotions</a>
            </li>
            <li>
              <a href="#">Specials</a>
            </li>
            <li>
              <a href="#">Careers</a>
            </li>
          </ul>
        </div>
        <div class="col-md-2">
          <h3>CONTACT</h3>
          <ul>
            <li>
              <p>Delivery Hotline:</p>
              <p>6385 9122 / 6385 9133</p>
              <p>Outlets</p>
            </li>
          </ul>
        </div>
        <div class="col-md-3">
          <h3>SHARE WITH US</h3>
          <ul>
            <li>
              <a class="facebook" href="#"></a>
              <a class="twitter" href="#"></a>
              <a class="instagram" href="#"></a>
            </li>
            <li><p class="copy-right">&copy; LEE WEE & BROTHERS' PTE LTD.</p></li>
          </ul>
        </div>
      </div>
  </footer>
</div>