<!-- Mobile Viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<!-- Force IE to render best possible view -->
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

<!-- FONT -->
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,300,600,700' rel='stylesheet' type='text/css'>

<!-- CSS -->
<link rel="stylesheet" href="lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="lib/bootstrap/dist/css/bootstrap-theme.min.css" />

<link rel="stylesheet" href="css/style.css" />

<!-- JS Libraries -->
<script type="text/javascript" src="lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="js/main.js"></script>
