<div id="page-wrapper">
  <div id="header-wrapper" class="container-fluid">
    <header id="main-header" class="container">
      <div class="row">
        <div class="col-md-3">
          <button class="search-btn"></button>
          <input type="text" id="search" name="search" placeholder="SEARCH" />
        </div>
        
        <div class="col-md-4 col-md-offset-5">
          <div class="header-content">
            <div id="header-links"><a href="join.shtml" class="join">JOIN</a> / <a href="login.shtml" class="sign-in">SIGN IN</a></div>
            <div id="header-cart-info">
                <div id="cart-icon"><img src="images/icons/cart-img.png" alt="Cart icon"><div class="white-divider"></div></div>  
                <div id="cart-item-price">
                  <span class="cart-items-count">0</span><span class="cart-items-count-label"> ITEM(S) -</span> 
                  <span class="cart-price-label">$</span><span class="cart-price">0.00</span>
                </div> 
            </div>
          </div>
        </div>
      </div>
    </header>
  </div>

  <div class="container-fluid" id="main-content">
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-md-offset-4 logo-container">
          <a href="index.shtml"><img src="images/logo/main-logo.png" alt="Lee Wee Brothers Logo" class="main-logo"></a>
        </div>
      </div>
      <div class="space20"></div>
      <div class="row">
        <div class="col-md-12 nav-container">
          <hr class="nav-hr">
          <nav class="main-nav">
            <ul class="main-menu">
              <li class="about">
                <a href="#">ABOUT US</a>
                <ul class="sub-menu">
                  <li>
                    <a href="#">Our Story</a>
                  </li>
                  <li>
                    <a href="#">Histroy</a>
                  </li>
                  <li>
                    <a href="#">The Lee Wee Difference</a>
                  </li>
                </ul>
              </li>
              <li class="food">
                <a href="#">OUR FOOD</a>
                <ul class="sub-menu six">
                  <li>
                    <a href="#">Otah</a>
                  </li>
                  <li>
                    <a href="#">Lunch Boxes</a>
                  </li>
                  <li>
                    <a href="#">Satay</a>
                  </li>
                  <li>
                    <a href="#">Snacks & Nibbles</a>
                  </li>
                  <li>
                    <a href="#">Local Flavours</a>
                  </li>
                  <li>
                    <a href="#">Condiments</a>
                  </li>
                </ul>
              </li>
              <li class="catering">
                <a href="#">CATERING</a>
                <ul class="sub-menu two">
                  <li>
                    <a href="#">Mini Buffet</a>
                  </li>
                  <li>
                    <a href="#">Others</a>
                  </li>
                </ul>
              </li>
              <li class="delivery">
                <a href="#">DELIVERY</a>
                <ul class="sub-menu two">
                  <li>
                    <a href="deliverytime.shtml">Time Slots</a>
                  </li>
                  <li>
                    <a href="#">Terms & Conditions</a>
                  </li>
                </ul>
              </li>
              <li class="outlets"><a href="#">OUTLETS</a></li>
              <li class="order">
                <a href="#">ORDER ONLINE</a>
                <ul class="sub-menu two">
                  <li>
                    <a href="#">Check Out & Payment</a>
                  </li>
                  <li>
                    <a href="#">FAQs</a>
                  </li>
                </ul>
              </li>
              <li class="promo"><a href="#">PROMOTION</a></li>
              <li class="career"><a href="careers.shtml">CAREERS</a></li>
              <li class="contact"><a href="#">CONTACT</a></li>
            </ul>
          </nav>
          <hr class="nav-hr">
        </div>
      </div>
      <div class="space20"></div>
    </div>
  </div>
