<div id="header-wrapper" class="container-fluid">
  <header id="main-header" class="container">
    <div class="row">
      <div class="col-md-3">
        <button class="search-btn"></button>
        <input type="text" id="search" name="search" placeholder="SEARCH" />
      </div>
      
      <div class="col-md-4 col-md-offset-5">
        <div class="header-content">
          <div id="header-links"><a href="#" class="join">JOIN</a> / <a href="#" class="sign-in">SIGN IN</a></div>
          <div id="header-cart-info">
              <div id="cart-icon"><img src="images/icons/cart-img.png" alt="Cart icon"><div class="white-divider"></div></div>  
              <div id="cart-item-price">
                <span class="cart-items-count">0</span><span class="cart-items-count-label"> ITEM(S) -</span> 
                <span class="cart-price-label">$</span><span class="cart-price">0.00</span>
              </div> 
          </div>
        </div>
      </div>
    </div>
  </header>
</div>


