<div id="header-wrapper" class="container-fluid">
  <header id="main-header" class="container">
    <div class="row">
      <div class="col-md-3">
        <button class="search-btn"></button>
        <input type="text" id="search" name="search" placeholder="SEARCH" />
      </div>
      
      <div class="col-md-4 col-md-offset-5">
        <div class="header-content">
          <div id="header-links"><a href="#" class="join">JOIN</a> / <a href="#" class="sign-in">SIGN IN</a></div>
          <div id="header-cart-info">
              <div id="cart-icon"><img src="images/icons/cart-img.png" alt="Cart icon"><div class="white-divider"></div></div>  
              <div id="cart-item-price">
                <span class="cart-items-count">0</span><span class="cart-items-count-label"> ITEM(S) -</span> 
                <span class="cart-price-label">$</span><span class="cart-price">0.00</span>
              </div> 
          </div>
        </div>
      </div>
    </div>
  </header>
</div>

<div class="container-fluid" id="main-content">
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-md-offset-4 logo-container">
          <a href="index.shtml"><img src="images/logo/main-logo.png" alt="Lee Wee Brothers Logo" class="main-logo"></a>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 nav-container">
          <hr class="nav-hr">
          <nav class="main-nav">
            <ul>
              <li><a href="#">ABOUT US</a></li>
              <li><a href="#">OUR FOOD</a></li>
              <li><a href="#">CATERING</a></li>
              <li><a href="#">DELIVERY</a></li>
              <li><a href="#">OUTLETS</a></li>
              <li><a href="#">ORDER ONLINE</a></li>
              <li><a href="#">PROMOTION</a></li>
              <li><a href="#">CAREERS</a></li>
              <li><a href="#">CONTACT</a></li>
            </ul>
          </nav>
          <hr class="nav-hr">
        </div>
      </div>
    </div>
  </div>
